//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalDetail
    {
        public int CallNumber { get; set; }
        public int StudentId { get; set; }
        public System.DateTime DateRent { get; set; }
        public System.DateTime DatePay { get; set; }
        public Nullable<int> LateFee { get; set; }
        public string IssueStatus { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<int> FeePay { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
